### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no argon2 in java.library.path

### ISSUE THREAD

**Issue by Faltenreich** [signalapp/Argon2#9]
I receive the following build error when trying to use the Android library (13.1) in a JUnit test:

```
java.lang.UnsatisfiedLinkError: no argon2 in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.signal.argon2.Argon2Native.<clinit>(Argon2Native.java:8)
	at org.signal.argon2.Argon2.hash(Argon2.java:130)
```

**Comment by alan-signal** [comment]
Hi, this is because this project is not intended for desktop environments, only android and iOS and the desktop dll/so/dylib library binaries are not built or included. Only .so files for arm.

Notice all of the android tests in this project are instrumentation tests.

My suggestions:

- Make your test an instrumentation test, and/or;
- Do not have many of your tests reliant on running this actual Argon2 implementation, abstract it, or mock it. It itself is already well tested, so many one instrumentation test checking your abstraction calls Argon2 correctly is all that is required.
